version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: fintrack_backend

    ports:
      - "5000:5000"

    env_file:
      - ./Backend/.env

    restart: always

  frontend:
    build: ./Frontend

    container_name: fintrack_frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always