version: "3"

services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env

  frontend:
    build: ./Frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend